### ISSUE TITLE
Problem using clarifai

### ISSUE THREAD

**Issue by archana-banga-20** [darrynten/clarifai-php#40]
1: We are not able to add/merge concepts later after creating a custom model it throws an error.
2: It is not exactly training our model, just writing a train command it says model trained  successfully based on no inputs, we are not exactly getting how to train our model.
3:Most Important while getting a predictions for an image it returns a prediction of all the concepts stored with our model which actually are not correct.
For Example- For My Pets Model my  concepts are dog and cat and while predicting any  dog image it returns prediction value for dog as 0.24.. and cat 0.26.
our prediction for dog must be higher than cat which is not.
Kindly help us how exactly clarifai is working.

**Comment by jared-clarifai** [comment]
Hi @anya-123 - can you paste the code for #1 here and the error?

For #2, a model training is based on concepts that you add to Inputs, either as positives or negatives. Any new additions to inputs would be taken into account here, though you can also train a model whenever you'd like, even when nothing has been changed.

#3 means that you probably need to add more training Inputs to the system since the system isn't able to distinguish between the concepts yet. You'll want to add at least 20-30 images for each.

**Comment by anya-123** [comment]
Hi Jared Lerner,
PFA for merge concepts to a model code and a document stating error .

[ErrorPage.docx](https://github.com/darrynten/clarifai-php/files/1030898/ErrorPage.docx)

[mergeModelConcepts.docx](https://github.com/darrynten/clarifai-php/files/1030894/mergeModelConcepts.docx)

**Comment by jared-clarifai** [comment]
@darrynten Any thoughts on this error?

**Comment by darrynten** [comment]
@vojtik - is this the issue you mentioned to me?

**Comment by vojtik** [comment]
@darrynten <https://github.com/darrynten> yes, i'm preparing commit right
now

2017-05-29 14:19 GMT+03:00 Darryn Ten <notifications@github.com>:

**Comment by anya-123** [comment]
Do inform me when you commit that.

**Comment by mxnr** [comment]
@anya-123 fix merged, please run composer update. Thanks!

**Comment by dev-archanabanga** [comment]
In RequestHandler.php Changing this line worked for me.
if ($method === 'POST' ) {
if ($method === 'POST' || $method === 'PATCH' || $method === 'DELETE'){ 

Thank You for your support.

**Comment by mxnr** [comment]
@archana-banga-20 hey! We just realized the same patch. Please update to 0.9.3 version.
